import { Phase } from "./cycleEngine";

export interface DayInsight {
  cycleDay: number;
  phase: Phase;
  hormoneNote: string;
  physicalExpectation: string;
  mentalExpectation: string;
  emotionalNote: string;
  energyLevel: "very_low" | "low" | "moderate" | "rising" | "high" | "declining";
  focusLevel: "poor" | "moderate" | "good" | "sharp";
  actionTip: string;
  tomorrowPreview: string;
}

const library: DayInsight[] = [
  {
    cycleDay: 1,
    phase: "menstrual",
    hormoneNote: "Estrogen and progesterone hit zero today — your period begins.",
    physicalExpectation: "Heaviest bleeding and strongest cramps usually hit on day 1.",
    mentalExpectation: "Brain fog and low motivation are driven by very low estrogen today.",
    emotionalNote: "Low hormones and pain signals make emotional regulation harder today.",
    energyLevel: "very_low",
    focusLevel: "poor",
    actionTip: "Rest as much as possible and eat iron-rich food tonight.",
    tomorrowPreview: "Day 2 cramps and bleeding typically peak before easing.",
  },
  {
    cycleDay: 2,
    phase: "menstrual",
    hormoneNote: "Estrogen stays at its lowest — bleeding and cramps peak today.",
    physicalExpectation: "Expect the heaviest flow and sharpest cramping of your cycle today.",
    mentalExpectation: "Concentration is harder than usual due to very low estrogen today.",
    emotionalNote: "Cramping and fatigue can make emotional sensitivity run high today.",
    energyLevel: "very_low",
    focusLevel: "poor",
    actionTip: "Stay warm, reduce exertion, and prioritize iron-rich food today.",
    tomorrowPreview: "Day 3 cramps typically ease as estrogen begins its slow rise.",
  },
  {
    cycleDay: 3,
    phase: "menstrual",
    hormoneNote: "Estrogen begins its slow rise — bleeding is starting to ease.",
    physicalExpectation: "Cramps and flow usually lighten noticeably by day 3.",
    mentalExpectation: "Mental fog may begin to lift slightly as estrogen ticks up today.",
    emotionalNote: "Emotional steadiness starts returning as pain eases and estrogen rises.",
    energyLevel: "low",
    focusLevel: "poor",
    actionTip: "A short gentle walk today can reduce cramping and boost circulation.",
    tomorrowPreview: "Day 4 usually brings noticeably lighter flow and returning energy.",
  },
  {
    cycleDay: 4,
    phase: "menstrual",
    hormoneNote: "Estrogen rises gradually — flow is lighter and energy is returning.",
    physicalExpectation: "Most people notice significantly lighter bleeding by today.",
    mentalExpectation: "Thinking starts feeling a little clearer as hormones stabilize today.",
    emotionalNote: "Mood lifts noticeably as hormones recover and bleeding lightens today.",
    energyLevel: "low",
    focusLevel: "moderate",
    actionTip: "Gentle activity is fine today — listen to how your body responds.",
    tomorrowPreview: "Day 5 is often the last light day before your period ends.",
  },
  {
    cycleDay: 5,
    phase: "menstrual",
    hormoneNote: "Estrogen continues rising — your period is ending and energy returns.",
    physicalExpectation: "Flow is usually light or spotting only by today.",
    mentalExpectation: "Mental clarity begins improving as hormones climb toward the follicular phase.",
    emotionalNote: "Emotional tone brightens alongside rising estrogen as your period ends.",
    energyLevel: "low",
    focusLevel: "moderate",
    actionTip: "Start reintroducing normal activity as your energy allows today.",
    tomorrowPreview: "Day 6 marks the follicular phase — energy and focus start building.",
  },
  {
    cycleDay: 6,
    phase: "follicular",
    hormoneNote: "Rising estrogen begins rebuilding your uterine lining today.",
    physicalExpectation: "Energy and stamina start picking up noticeably from today.",
    mentalExpectation: "Mental sharpness begins its steady climb — focus improves each day.",
    emotionalNote: "Rising estrogen brings more emotional stability and social ease today.",
    energyLevel: "rising",
    focusLevel: "moderate",
    actionTip: "Good day to plan ahead — your capacity for focused work is growing.",
    tomorrowPreview: "Day 7 brings continued energy and mood improvement.",
  },
  {
    cycleDay: 7,
    phase: "follicular",
    hormoneNote: "Estrogen rises steadily — follicles are developing toward ovulation.",
    physicalExpectation: "Physical energy is returning consistently and fatigue is mostly gone.",
    mentalExpectation: "Focus and motivation are noticeably sharper than last week.",
    emotionalNote: "Mood and emotional resilience continue improving with rising estrogen today.",
    energyLevel: "rising",
    focusLevel: "good",
    actionTip: "Tackle moderate tasks today — energy is steady enough for real work.",
    tomorrowPreview: "Day 8 brings even steadier energy as estrogen continues climbing.",
  },
  {
    cycleDay: 8,
    phase: "follicular",
    hormoneNote: "Estrogen is building strongly — your body is preparing to ovulate.",
    physicalExpectation: "Physical capacity is near its weekly peak today.",
    mentalExpectation: "Concentration and decision-making feel sharper than most days this cycle.",
    emotionalNote: "Positive mood and emotional confidence are building toward their monthly peak.",
    energyLevel: "rising",
    focusLevel: "good",
    actionTip: "High-value tasks, hard decisions, and new projects fit well today.",
    tomorrowPreview: "Day 9 continues the upward energy and focus trend.",
  },
  {
    cycleDay: 9,
    phase: "follicular",
    hormoneNote: "Estrogen surges continue — ovulation is roughly 5 days away.",
    physicalExpectation: "Strength and endurance are near their monthly high today.",
    mentalExpectation: "Verbal fluency and social ease tend to peak in this window.",
    emotionalNote: "Social confidence and emotional warmth are near their monthly high today.",
    energyLevel: "high",
    focusLevel: "good",
    actionTip: "Collaborate, present, or tackle complex problems — conditions are optimal today.",
    tomorrowPreview: "Day 10 brings peak pre-ovulatory energy and mental sharpness.",
  },
  {
    cycleDay: 10,
    phase: "follicular",
    hormoneNote: "Estrogen is near its monthly peak — ovulation is approaching fast.",
    physicalExpectation: "Energy and strength are at their highest point of this cycle.",
    mentalExpectation: "Thinking is sharpest and focus most reliable today.",
    emotionalNote: "Peak estrogen supports the most positive mood of the month today.",
    energyLevel: "high",
    focusLevel: "sharp",
    actionTip: "Use this window for demanding work, intense exercise, or creative output.",
    tomorrowPreview: "Day 11 continues peak performance before the ovulation window opens.",
  },
  {
    cycleDay: 11,
    phase: "follicular",
    hormoneNote: "LH surge is building — ovulation is 3–4 days away.",
    physicalExpectation: "Energy stays high but may plateau as ovulation approaches.",
    mentalExpectation: "Mental acuity and confidence remain at their monthly high today.",
    emotionalNote: "Emotional confidence and social ease remain at their monthly high today.",
    energyLevel: "high",
    focusLevel: "sharp",
    actionTip: "Good day for negotiations, presentations, or high-stakes decisions.",
    tomorrowPreview: "Day 12 marks the start of the pre-ovulatory transition.",
  },
  {
    cycleDay: 12,
    phase: "follicular",
    hormoneNote: "LH begins surging — ovulation is 2–3 days away.",
    physicalExpectation: "Energy is high and physical performance is near its monthly peak.",
    mentalExpectation: "Confidence and social energy are near their monthly peak today.",
    emotionalNote: "Warmth, confidence, and emotional openness are near their strongest today.",
    energyLevel: "high",
    focusLevel: "sharp",
    actionTip: "Leverage your peak social energy for important conversations today.",
    tomorrowPreview: "Day 13 is typically the last day before ovulation begins.",
  },
  {
    cycleDay: 13,
    phase: "follicular",
    hormoneNote: "LH surge is imminent — cervical mucus is at its clearest today.",
    physicalExpectation: "Physical energy is strong; you may feel a slight lower abdominal pull.",
    mentalExpectation: "Clarity and motivation remain at their monthly high today.",
    emotionalNote: "Social and emotional energy are at their peak before ovulation.",
    energyLevel: "high",
    focusLevel: "good",
    actionTip: "Wrap up demanding tasks before ovulation shifts your energy tomorrow.",
    tomorrowPreview: "Day 14 marks ovulation — your peak energy window opens.",
  },
  {
    cycleDay: 14,
    phase: "ovulation",
    hormoneNote: "LH peaks today — ovulation is occurring right now.",
    physicalExpectation: "Energy is at its monthly peak; some people feel a brief pelvic twinge.",
    mentalExpectation: "Confidence, clarity, and social drive all peak together today.",
    emotionalNote: "Emotional confidence peaks alongside LH — most people feel open and social today.",
    energyLevel: "high",
    focusLevel: "sharp",
    actionTip: "Use peak energy for demanding exercise, creative work, or big decisions.",
    tomorrowPreview: "Day 15 energy stays high as the ovulation window continues.",
  },
  {
    cycleDay: 15,
    phase: "ovulation",
    hormoneNote: "Estrogen starts dropping as progesterone rises post-ovulation today.",
    physicalExpectation: "Energy is still at its highest but the post-ovulation shift starts soon.",
    mentalExpectation: "Peak social and verbal energy continues today before the luteal shift.",
    emotionalNote: "High estrogen keeps emotional tone positive and socially energetic today.",
    energyLevel: "high",
    focusLevel: "sharp",
    actionTip: "Good day for anything requiring high energy or strong communication.",
    tomorrowPreview: "Day 16 ends the ovulation window and energy begins its gradual decline.",
  },
  {
    cycleDay: 16,
    phase: "ovulation",
    hormoneNote: "Progesterone begins rising — the luteal phase transition starts today.",
    physicalExpectation: "Energy is strong today but the post-ovulatory shift begins now.",
    mentalExpectation: "Focus remains good; emotional sensitivity may start increasing from today.",
    emotionalNote: "Emotional warmth remains high but the luteal shift begins soon.",
    energyLevel: "high",
    focusLevel: "good",
    actionTip: "Wind down intense output before energy begins its natural decline.",
    tomorrowPreview: "Day 17 starts the luteal phase — energy and mood shift gradually.",
  },
  {
    cycleDay: 17,
    phase: "luteal",
    hormoneNote: "Progesterone rises steadily — your body is preparing for possible implantation.",
    physicalExpectation: "Energy is still good but stamina feels slightly less reliable today.",
    mentalExpectation: "Focus holds well today; mood is generally stable in early luteal.",
    emotionalNote: "Progesterone's calming effect makes emotional steadiness solid today.",
    energyLevel: "moderate",
    focusLevel: "good",
    actionTip: "Shift to steady consistent work rather than high-intensity output today.",
    tomorrowPreview: "Day 18 continues progesterone rise with mild physical changes beginning.",
  },
  {
    cycleDay: 18,
    phase: "luteal",
    hormoneNote: "Both estrogen and progesterone are elevated — body feels fuller today.",
    physicalExpectation: "Mild bloating or breast tenderness may begin today.",
    mentalExpectation: "Thinking is still clear; detail and analytical work feel reliable today.",
    emotionalNote: "Progesterone's calming effect keeps emotional tone stable today.",
    energyLevel: "moderate",
    focusLevel: "good",
    actionTip: "Detail-oriented tasks fit well today — analytical thinking is reliable.",
    tomorrowPreview: "Day 19 brings continued hormonal shifts with subtle mood changes.",
  },
  {
    cycleDay: 19,
    phase: "luteal",
    hormoneNote: "Progesterone peaks around now — the highest point of your cycle.",
    physicalExpectation: "Bloating and fatigue may feel more noticeable as progesterone peaks today.",
    mentalExpectation: "Thinking is calm but slightly slower — good for reflective or routine work.",
    emotionalNote: "Mood is generally calm today, though some people feel slightly flat.",
    energyLevel: "moderate",
    focusLevel: "moderate",
    actionTip: "Steady lower-intensity work suits today better than fast-paced demands.",
    tomorrowPreview: "Day 20 brings continued high progesterone with possible mild fatigue.",
  },
  {
    cycleDay: 20,
    phase: "luteal",
    hormoneNote: "Progesterone remains high — body temperature is slightly elevated today.",
    physicalExpectation: "Physical heaviness and mild fatigue are common today.",
    mentalExpectation: "Mental energy feels slightly dampened by peak progesterone today.",
    emotionalNote: "Emotional tone may feel muted or low-key as progesterone peaks today.",
    energyLevel: "moderate",
    focusLevel: "moderate",
    actionTip: "Prioritize quality over quantity today, and protect your sleep tonight.",
    tomorrowPreview: "Day 21 marks the transition toward late luteal and hormone decline.",
  },
  {
    cycleDay: 21,
    phase: "luteal",
    hormoneNote: "Estrogen and progesterone begin dropping if no pregnancy occurred today.",
    physicalExpectation: "Energy may feel less consistent as hormones begin their decline.",
    mentalExpectation: "Mood and focus may feel more variable today as hormones shift.",
    emotionalNote: "Mood stability may begin fluctuating as estrogen and progesterone decline.",
    energyLevel: "declining",
    focusLevel: "moderate",
    actionTip: "Protect your sleep window tonight — recovery matters more from here.",
    tomorrowPreview: "Day 22 enters the PMS-sensitive window — expect more variability.",
  },
  {
    cycleDay: 22,
    phase: "luteal",
    hormoneNote: "Both estrogen and progesterone declining — PMS symptoms can begin today.",
    physicalExpectation: "Fatigue, bloating, and cravings may increase as hormones drop today.",
    mentalExpectation: "Emotional sensitivity rises as estrogen falls — small stressors feel bigger.",
    emotionalNote: "Low estrogen makes feelings run closer to the surface today.",
    energyLevel: "declining",
    focusLevel: "moderate",
    actionTip: "Reduce decision load today and schedule lighter tasks where possible.",
    tomorrowPreview: "Day 23 continues the hormone drop that drives PMS symptoms.",
  },
  {
    cycleDay: 23,
    phase: "luteal",
    hormoneNote: "Estrogen keeps declining — serotonin tends to dip alongside it today.",
    physicalExpectation: "Physical discomfort like headaches or bloating can increase today.",
    mentalExpectation: "Mood may feel lower or more reactive than your usual baseline today.",
    emotionalNote: "Mood feels more reactive today as serotonin dips alongside estrogen.",
    energyLevel: "declining",
    focusLevel: "moderate",
    actionTip: "Gentle movement and reduced screen time can support mood stability today.",
    tomorrowPreview: "Day 24 is often when PMS symptoms feel most noticeable.",
  },
  {
    cycleDay: 24,
    phase: "luteal",
    hormoneNote: "Hormones are near their pre-period low — cortisol sensitivity is highest now.",
    physicalExpectation: "Bloating, breast tenderness, and fatigue often peak around day 24.",
    mentalExpectation: "Stress hits harder than usual today because estrogen is very low.",
    emotionalNote: "Low hormone levels make emotional reactions stronger than usual today.",
    energyLevel: "declining",
    focusLevel: "poor",
    actionTip: "Reduce commitments today — this is the hardest window of your cycle.",
    tomorrowPreview: "Day 25 continues peak PMS; your period is about 4 days away.",
  },
  {
    cycleDay: 25,
    phase: "luteal",
    hormoneNote: "Estrogen and progesterone near their lowest pre-period levels today.",
    physicalExpectation: "Pre-period cramping, fatigue, or low back ache may begin today.",
    mentalExpectation: "Emotional load feels heavier and reactivity is elevated today.",
    emotionalNote: "Pre-period hormonal drop can make emotions feel heavier today.",
    energyLevel: "low",
    focusLevel: "poor",
    actionTip: "Prioritize sleep, hydration, and light activity over social obligations today.",
    tomorrowPreview: "Day 26 — period is 3 days away; symptoms may ease slightly.",
  },
  {
    cycleDay: 26,
    phase: "luteal",
    hormoneNote: "Hormone levels are very low — your body is preparing to shed the lining.",
    physicalExpectation: "Pre-period symptoms like cramps or low back ache are common today.",
    mentalExpectation: "Irritability and low mood often peak in this final luteal window.",
    emotionalNote: "Irritability and emotional heaviness peak because estrogen is at its lowest.",
    energyLevel: "low",
    focusLevel: "poor",
    actionTip: "Warm food, earlier sleep, and minimal decision-making support today.",
    tomorrowPreview: "Day 27 — period is 2 days away; hold steady.",
  },
  {
    cycleDay: 27,
    phase: "luteal",
    hormoneNote: "Progesterone is near zero — uterine contractions may begin lightly today.",
    physicalExpectation: "Light cramping or spotting may appear today as your period nears.",
    mentalExpectation: "Emotional sensitivity remains high today — small stressors feel disproportionate.",
    emotionalNote: "Even small stressors can feel disproportionate today as hormones near zero.",
    energyLevel: "low",
    focusLevel: "poor",
    actionTip: "Keep your schedule light and prepare for your period arriving soon.",
    tomorrowPreview: "Day 28 — period arrives very soon; relief follows within hours.",
  },
  {
    cycleDay: 28,
    phase: "luteal",
    hormoneNote: "All hormones are at their cycle low — your period is arriving soon.",
    physicalExpectation: "Cramps or spotting signal your period is imminent today.",
    mentalExpectation: "Mental load often feels heaviest right before bleeding starts.",
    emotionalNote: "Emotional tension is highest right before bleeding — relief comes with day 1.",
    energyLevel: "very_low",
    focusLevel: "poor",
    actionTip: "Rest, warmth, and gentle nutrition — relief comes when bleeding starts.",
    tomorrowPreview: "Day 1 — your period begins and PMS relief usually follows within hours.",
  },
];

/**
 * Returns day-specific insight data for any cycle day.
 * Days beyond 28 are clamped to 28 (deep luteal, longer cycles).
 */
export function getDayInsight(cycleDay: number): DayInsight {
  const clamped = Math.max(1, Math.min(28, cycleDay));
  return library[clamped - 1]!;
}
