const homeScreen = {
  cycle: [
    {
      day: 1,
      phase: "menstrual",
      top: "On your period",
      fertility: "Pregnancy unlikely today",
      feeling: "You might feel low energy today",
      cta: "Take it easy today",
    },
    {
      day: 2,
      phase: "menstrual",
      top: "On your period",
      fertility: "Pregnancy unlikely today",
      feeling: "You might feel tired today",
      cta: "Go slow today",
    },
    {
      day: 3,
      phase: "menstrual",
      top: "On your period",
      fertility: "Low chance of pregnancy",
      feeling: "You may feel slightly better today",
      cta: "Ease back gently",
    },
    {
      day: 4,
      phase: "menstrual",
      top: "Period ending soon",
      fertility: "Low chance of pregnancy",
      feeling: "You might feel more stable today",
      cta: "Start fresh slowly",
    },
    {
      day: 5,
      phase: "menstrual",
      top: "End of period",
      fertility: "Low chance of pregnancy",
      feeling: "You may feel refreshed today",
      cta: "Reset your routine",
    },
    {
      day: 6,
      phase: "follicular",
      top: "Fresh start",
      fertility: "Low chance of pregnancy",
      feeling: "You might feel more active today",
      cta: "Start fresh today",
    },
    {
      day: 7,
      phase: "follicular",
      top: "Energy rising",
      fertility: "Low chance of pregnancy",
      feeling: "You might feel motivated today",
      cta: "Take initiative",
    },
    {
      day: 8,
      phase: "follicular",
      top: "Momentum building",
      fertility: "Low chance of pregnancy",
      feeling: "You may feel productive today",
      cta: "Stay consistent",
    },
    {
      day: 9,
      phase: "follicular",
      top: "In your flow",
      fertility: "Chance of pregnancy is increasing",
      feeling: "You might feel inspired today",
      cta: "Explore ideas",
    },
    {
      day: 10,
      phase: "follicular",
      top: "Ovulation approaching",
      fertility: "Chance of pregnancy is increasing",
      feeling: "You may feel confident today",
      cta: "Take bold steps",
    },
    {
      day: 11,
      phase: "follicular",
      top: "Almost peak phase",
      fertility: "Chance of pregnancy is increasing",
      feeling: "You might feel sharp today",
      cta: "Connect & lead",
    },
    {
      day: 12,
      phase: "follicular",
      top: "Near ovulation",
      fertility: "High chance of pregnancy today",
      feeling: "You may feel powerful today",
      cta: "Take action",
    },
    {
      day: 13,
      phase: "follicular",
      top: "Peak is near",
      fertility: "High chance of pregnancy today",
      feeling: "You might feel your best today",
      cta: "Go all in",
    },
    {
      day: 14,
      phase: "ovulation",
      top: "Ovulation day",
      fertility: "High chance of pregnancy today",
      feeling: "You might feel confident today",
      cta: "Make the most of today",
    },
    {
      day: 15,
      phase: "ovulation",
      top: "Peak energy",
      fertility: "High chance of pregnancy today",
      feeling: "You may feel magnetic today",
      cta: "Socialize & express",
    },
    {
      day: 16,
      phase: "ovulation",
      top: "Post ovulation",
      fertility: "Chance of pregnancy is decreasing",
      feeling: "You might feel balanced today",
      cta: "Maintain momentum",
    },
    {
      day: 17,
      phase: "luteal",
      top: "Transition phase",
      fertility: "Low chance of pregnancy",
      feeling: "You may feel steady today",
      cta: "Stay focused",
    },
    {
      day: 18,
      phase: "luteal",
      top: "Slowing down",
      fertility: "Low chance of pregnancy",
      feeling: "You might feel calm today",
      cta: "Work mindfully",
    },
    {
      day: 19,
      phase: "luteal",
      top: "Energy dipping slightly",
      fertility: "Low chance of pregnancy",
      feeling: "You may feel less social today",
      cta: "Prioritize yourself",
    },
    {
      day: 20,
      phase: "luteal",
      top: "Reflective phase",
      fertility: "Low chance of pregnancy",
      feeling: "You might feel introspective",
      cta: "Check in with yourself",
    },
    {
      day: 21,
      phase: "luteal",
      top: "Slow mode",
      fertility: "Low chance of pregnancy",
      feeling: "You may feel more sensitive today",
      cta: "Slow down",
    },
    {
      day: 22,
      phase: "luteal",
      top: "Energy declining",
      fertility: "Low chance of pregnancy",
      feeling: "You might feel low energy",
      cta: "Reduce workload",
    },
    {
      day: 23,
      phase: "luteal",
      top: "Pre-period phase",
      fertility: "Low chance of pregnancy",
      feeling: "You may feel emotionally aware",
      cta: "Give yourself space",
    },
    {
      day: 24,
      phase: "luteal",
      top: "Slower pace",
      fertility: "Low chance of pregnancy",
      feeling: "You might feel drained",
      cta: "Rest more",
    },
    {
      day: 25,
      phase: "luteal",
      top: "Deep rest phase",
      fertility: "Low chance of pregnancy",
      feeling: "You may feel withdrawn",
      cta: "Pause & breathe",
    },
    {
      day: 26,
      phase: "luteal",
      top: "Almost reset",
      fertility: "Pregnancy unlikely today",
      feeling: "You might feel very low energy",
      cta: "Do less today",
    },
    {
      day: 27,
      phase: "luteal",
      top: "Pre-period",
      fertility: "Pregnancy unlikely today",
      feeling: "You may feel sensitive today",
      cta: "Be gentle with yourself",
    },
    {
      day: 28,
      phase: "luteal",
      top: "Cycle reset",
      fertility: "Pregnancy unlikely today",
      feeling: "You might feel ready to rest",
      cta: "Wind down",
    },
  ],
};
